"""Small pinned-source structural fixtures, not compiler-level correctness claims."""
CASES = {
 '.ps1': 'function target { return 1 }\nfunction entry { target }\nentry\n',
 '.sh': 'target() { echo ok; }\nentry() { target; }\nentry\n',
 '.sql': 'CREATE TABLE users (id INTEGER); CREATE VIEW active_users AS SELECT id FROM users;',
 '.groovy': 'class Sample { int target() { 1 }; int entry() { target() } }',
 '.dart': 'int target() { return 1; } int entry() { return target(); }',
 '.zig': 'fn target() i32 { return 1; } fn entry() i32 { return target(); }',
 '.ex': 'defmodule Sample do\n def target(), do: 1\n def entry(), do: target()\nend',
 '.jl': 'function target()\n 1\nend\nfunction entry()\n target()\nend',
 '.m': '@interface Sample\n- (void)target;\n@end\n@implementation Sample\n- (void)target {}\n@end',
 '.v': 'module child(input a, output b); assign b=a; endmodule\nmodule top(input a, output b); child u(a,b); endmodule',
 '.f90': 'module sample\ncontains\nsubroutine target()\nend subroutine\nsubroutine entry()\ncall target()\nend subroutine\nend module',
 '.r': 'target <- function() { 1 }\nentry <- function() { target() }',
 '.erl': '-module(sample).\n-export([entry/0]).\ntarget() -> 1.\nentry() -> target().',
 '.tf': 'resource "null_resource" "first" {}\nresource "null_resource" "next" { depends_on = [null_resource.first] }',
 '.pas': 'unit Sample; interface procedure Target; implementation procedure Target; begin end; end.',
 '.ml': 'let target x = x + 1\nlet entry x = target x',
 '.lisp': '(defun target (x) (+ x 1))\n(defun entry (x) (target x))',
 '.sol': 'pragma solidity ^0.8.0; contract Sample { function target() public pure returns(uint) { return 1; } }',
 '.cbl': '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. SAMPLE.\n       PROCEDURE DIVISION.\n       MAIN.\n           PERFORM TARGET.\n       TARGET.\n           DISPLAY "OK".\n',
 '.vue': '<script>function target() { return 1; } function entry() { return target(); }</script><template><div /></template>',
 '.svelte': '<script>function target() { return 1; } function entry() { return target(); }</script><div />',
 '.astro': '---\nfunction target() { return 1; } function entry() { return target(); }\n---\n<div />',
 '.cshtml': '@using Sample\n@functions { public int Target() { return 1; } }',
 '.vb': 'Public Class Sample\n Public Function Target() As Integer\n Return 1\n End Function\nEnd Class',
 '.robot': '*** Keywords ***\nTarget\n    Log    OK\nEntry\n    Target\n',
 '.cls': 'public class Sample { public static Integer target() { return 1; } }',
}
