import assert from 'node:assert/strict';
import {Element} from './graph-explorer-drag-fixture.mjs';
import {viewport} from '../src/SMSR.App/WebAssets/graph-explorer-viewport.js';
const tools=new Element('div');
globalThis.document={createElement:tag=>new Element(tag),querySelector:()=>tools};
const graph=new Element('div');graph.clientWidth=562;graph.clientHeight=420;graph.scrollLeft=graph.scrollTop=0;
const svg=new Element('svg'),canvas={width:1200,height:1100};
let dispose=viewport(graph,svg,canvas);
const [out,zoom,fit,label]=tools.children[0].children;
assert.equal(svg.style.width,'100%');assert.equal(svg.style.height,'100%');assert.equal(out.disabled,true);
assert.match(label.textContent,/전체 · 38%/);
zoom.event('click');assert.equal(out.disabled,false);assert.equal(svg.style.height,'630px');assert.ok(graph.scrollTop>0);
graph.clientWidth=547;graph.clientHeight=405;out.event('click');assert.equal(svg.style.width,'100%','native scrollbars must not change the shrink-to-fit threshold');
graph.clientWidth=562;graph.clientHeight=420;fit.event('click');zoom.event('click');
zoom.event('click');zoom.event('click');assert.ok(parseFloat(svg.style.width)>=canvas.width,'100% scale must be reachable for readable labels');
graph.scrollLeft=100;graph.scrollTop=200;out.event('click');assert.ok(parseFloat(svg.style.width)<canvas.width*1.5);
fit.event('click');assert.equal(svg.style.width,'100%');assert.equal(graph.scrollLeft,0);assert.equal(graph.scrollTop,0);
dispose();assert.equal(zoom.onclick,null);assert.equal(zoom.disabled,true);
const next=new Element('svg');dispose=viewport(graph,next,{width:880,height:570});
assert.equal(tools.children.length,1,'redraw must reuse the toolbar');zoom.event('click');assert.notEqual(next.style.width,'100%');assert.equal(svg.style.width,'100%','old SVG must not receive new commands');
for(let i=0;i<15;i++)zoom.event('click');assert.equal(zoom.disabled,true);assert.equal(parseFloat(next.style.width),880*3);
for(let i=0;i<15;i++)out.event('click');assert.equal(out.disabled,true);assert.equal(next.style.width,'100%');
dispose();console.log('PASS initial fit, readable zoom, native overflow sizing, shrink/fit, caps and toolbar cleanup');
