import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {previewDocument} from './find-simple-preview-fixture.mjs';
const docs=new URL('../docs/',import.meta.url),document=previewDocument();
const html=readFileSync(new URL('find-simple-preview-2026-10-02.html',docs),'utf8');
for(const id of document.nodes.keys())assert.ok(html.includes(`id="${id}"`),id);
assert.match(html,/<details id="connections" hidden>/);
assert.match(html,/<details id="tools">/);
assert.match(html,/가상 데이터/);
const context=vm.createContext({document});
for(const file of ['data','view','']){
  const name='find-simple-preview'+(file?'-'+file:'')+'.js';
  assert.ok(html.includes(name));
  const source=readFileSync(new URL(name,docs),'utf8');
  assert.ok(!/\b(fetch|XMLHttpRequest|WebSocket|localStorage)\b/.test(source));
  vm.runInContext(source,context,{filename:name});
}
const get=id=>document.nodes.get(id),run=s=>vm.runInContext(s,context);
assert.equal(get('count').textContent,'6개');
assert.equal(get('selection').children[0].textContent,'OrderService.cs');
assert.equal(get('graph').children[0].textContent,'OrderService.cs');
assert.equal(get('graph').children[1].children.length,2);
get('graph').children[1].children[0].children[1].onclick();
assert.equal(get('graph').children[0].textContent,'PaymentClient.ts');
run("selectPreview('order')");
const related=get('selection').children.find(n=>n.className==='related');
related.children[0].onclick();
assert.equal(get('selection').children[1].textContent,'PaymentClient.ts');
get('selection').children.find(n=>n.className.includes('source-action')).onclick();
assert.equal(get('source').open,true);assert.match(get('source-text').textContent,/gateway.send/);
get('query').value='없는 파일';run('searchPreview()');
assert.equal(get('count').textContent,'0개');assert.equal(get('connections').hidden,true);
get('query').value='';
const audio=get('filters').children.find(n=>n.dataset.kind==='audio');
get('filters').onclick({target:audio});
assert.equal(get('count').textContent,'1개');
document.querySelectorAll('.result')[0].onclick();
assert.equal(get('connections').hidden,true);
assert.match(get('selection').children.find(n=>n.className==='role').textContent,/아직 없습니다/);
assert.equal(audio.attributes['aria-pressed'],'true');
get('filters').onclick({target:get('filters').children[0]});assert.equal(get('count').textContent,'6개');
assert.equal(run('previewItems.every(n=>n.related.every(([id])=>previewItems.some(x=>x.id===id)))'),true);
console.log('PASS: sample search, filters, selection, links, source, unknown state; no browser layout verification');
