import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/SMSR.App/WebAssets/graph-explorer-labels.js', import.meta.url), 'utf8');
const { labelLines, kindName, kindClass, relationName } = await import('data:text/javascript,' + encodeURIComponent(source));
const name = 'graph-jdt-verification-2026-09-29.md';
assert.equal(labelLines(name).join(''), name);
assert.ok(labelLines(name).length > 1);
assert.equal(labelLines('한글 문서 제목').join(''), '한글 문서 제목');
assert.ok(labelLines('name: smsr-tracking description: Push a Codex task').some(line => line.includes('description:')));
assert.equal(kindName('heading'), '문서 내부 제목');
assert.equal(kindName('audio'), '음원');
assert.equal(kindName('video'), '영상');
assert.equal(relationName('CONTAINS'), '포함');
assert.equal(relationName('UNKNOWN'), 'UNKNOWN');
assert.equal(kindName('symbol'), '코드 심벌');
assert.equal(kindClass('symbol'), 'kind-code');
for (const kind of ['concept','requirement','rationale']) assert.equal(kindClass(kind), 'kind-document');
assert.equal(relationName('INHERITS'), '상속');
const { evidenceName, resolutionName } = await import('../src/SMSR.App/WebAssets/graph-explorer-evidence.js');
assert.equal(evidenceName({confidence:'EXTRACTED'}), '원문 근거');
assert.equal(evidenceName({confidence:'EXPLICIT'}), '원문 근거');
assert.equal(evidenceName({confidence:'INFERRED'}), '추론한 관계');
assert.equal(evidenceName({confidence:'AMBIGUOUS'}), '모호한 관계');
assert.equal(resolutionName({resolution:'INFERRED'}), '추론한 대상');
assert.equal(resolutionName({resolution:'FILE_ONLY'}), '파일까지만 확인');
console.log('graph explorer labels: OK');
